In [6]:
from curl_cffi import requests
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import talib as ta
import seaborn as sns
sns.set_theme(style="whitegrid")
import pickle
import duckdb as db

In [7]:
window = 20

In [ ]:
with open('/Users/gautamnaik/Developer/gmmm-backtester/data_download/n500_10yr_v1.pickle', 'rb') as f:
    stock_data = pickle.load(f)

with open('../../data/nifty_data.pkl', 'rb') as f:
    index_data = pickle.load(f)

with open('../../data/nifty_regimes_m.pkl', 'rb') as f:
    regime = pickle.load(f)
    
n200 = pd.read_csv("../../data/ind_nifty500list.csv")

In [9]:
index_data = index_data.reset_index().rename(columns={'index': 'Date', 'Close': 'Index_Close'})[['Date', 'Index_Close']]

In [10]:
index_data["Date"] = index_data['Date'].dt.tz_localize(None)
index_data["index_ret_1d"]= index_data['Index_Close'].pct_change(1)
index_data["index_ret_5d"]= index_data['Index_Close'].pct_change(5)
index_data["index_ret_20d"]= index_data['Index_Close'].pct_change(20)
# index_data["var"] = index_data['index_ret_1d'].rolling(window).var()
index_data["index_vol"] = index_data["index_ret_1d"].rolling(window).std()
index_data["index_vol_5d"] = index_data["index_ret_1d"].rolling(5).std()
index_data["index_vol_20d"] = index_data["index_ret_1d"].rolling(20).std()

In [11]:
stock_data["Date"].min(), stock_data["Date"].max()

(Timestamp('2015-09-16 00:00:00'), Timestamp('2025-09-15 00:00:00'))

In [12]:
index_data=index_data.set_index("Date")

In [13]:
full_idx = pd.date_range(index_data.index.min(), index_data.index.max(), freq="D")
index_data = index_data.reindex(full_idx)

In [14]:
index_data=index_data.bfill().ffill()
index_data

,Index_Close,index_ret_1d,index_ret_5d,index_ret_20d,index_vol,index_vol_5d,index_vol_20d
2007-09-17,4494.649902,0.011469,0.097349,0.261066,0.018438,0.014034,0.018438
2007-09-18,4546.200195,0.011469,0.097349,0.261066,0.018438,0.014034,0.018438
2007-09-19,4732.350098,0.040946,0.097349,0.261066,0.018438,0.014034,0.018438
2007-09-20,4747.549805,0.003212,0.097349,0.261066,0.018438,0.014034,0.018438
2007-09-21,4837.549805,0.018957,0.097349,0.261066,0.018438,0.014034,0.018438
...,...,...,...,...,...,...,...
2025-09-15,25069.199219,-0.001784,0.011950,0.017778,0.005349,0.002638,0.005349
2025-09-16,25239.099609,0.006777,0.014898,0.014558,0.005105,0.003290,0.005105
2025-09-17,25330.250000,0.003611,0.014301,0.013995,0.005087,0.003244,0.005087
2025-09-18,25423.599609,0.003685,0.016720,0.014892,0.005110,0.003133,0.005110
2025-09-19,25327.050781,-0.003798,0.008483,0.009700,0.005207,0.004351,0.005207

In [15]:
index_data=index_data.reset_index()
index_data=index_data.rename(columns={'index': 'Date'})

In [16]:
index_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6578 entries, 0 to 6577
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           6578 non-null   datetime64[ns]
 1   Index_Close    6578 non-null   float64
 2   index_ret_1d   6578 non-null   float64
 3   index_ret_5d   6578 non-null   float64
 4   index_ret_20d  6578 non-null   float64
 5   index_vol      6578 non-null   float64
 6   index_vol_5d   6578 non-null   float64
 7   index_vol_20d  6578 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 411.3 KB

In [17]:
stock_data.head()

        Date        Open        High         Low       Close   Volume  Symbol
0 2019-09-19  248.479767  260.903748  248.479767  260.903748  7109860  360ONE
1 2019-09-20  272.917023  273.943787  272.917023  273.943787  2760648  360ONE
2 2019-09-23  287.641022  287.641022  287.641022  287.641022    34096  360ONE
3 2019-09-24  302.015839  302.015839  302.015839  302.015839  2496652  360ONE
4 2019-09-25  317.109436  317.109436  286.922241  288.513733   530580  360ONE

In [18]:
# count number of zeroes in each column
(stock_data==0).sum()

Date         0
Open         0
High         0
Low          0
Close        0
Volume    2128
Symbol       0
dtype: Int64

In [19]:
# replace zeroes with NaN
stock_data = stock_data.replace(0, np.nan)

In [20]:
stock_data

,Date,Open,High,Low,Close,Volume,Symbol
0,2019-09-19,248.479767,260.903748,248.479767,260.903748,7109860.0,360ONE
1,2019-09-20,272.917023,273.943787,272.917023,273.943787,2760648.0,360ONE
2,2019-09-23,287.641022,287.641022,287.641022,287.641022,34096.0,360ONE
3,2019-09-24,302.015839,302.015839,302.015839,302.015839,2496652.0,360ONE
4,2019-09-25,317.109436,317.109436,286.922241,288.513733,530580.0,360ONE
...,...,...,...,...,...,...,...
976725,2025-09-09,1010.000000,1038.699951,1009.200012,1035.599976,1228793.0,ZYDUSLIFE
976726,2025-09-10,1040.550049,1049.849976,1033.000000,1039.599976,1086228.0,ZYDUSLIFE
976727,2025-09-11,1039.599976,1048.000000,1030.300049,1043.599976,537049.0,ZYDUSLIFE
976728,2025-09-12,1048.300049,1054.599976,1042.000000,1044.750000,559927.0,ZYDUSLIFE
976729,2025-09-15,1047.000000,1047.000000,1033.050049,1036.900024,391505.0,ZYDUSLIFE

In [21]:
# stock_data["Volume"] = stock_data.groupby('Symbol', group_keys=False)["Volume"].apply(lambda group: group.interpolate())
stock_data["Volume"] = stock_data.groupby('Symbol')["Volume"].transform(lambda x: x.interpolate())

In [22]:
(stock_data==0).sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Symbol    0
dtype: Int64

In [17]:
stock_data.groupby('Symbol').apply(lambda g: ta.OBV(g["Close"], g["Volume"]), include_groups=False).reset_index(level=0, drop=True)

0             46055.0
1            175602.0
2            141049.0
3            127442.0
4            112146.0
             ...
430042    682849209.0
430043    683935437.0
430044    684472486.0
430045    685032413.0
430046    684640908.0
Length: 430047, dtype: float64

In [18]:
stock_data.groupby('Symbol').apply(lambda g: ta.OBV(g["Close"], g["Volume"]), include_groups=False)

Symbol
ABB        0             46055.0
           1            175602.0
           2            141049.0
           3            127442.0
           4            112146.0
                        ...
ZYDUSLIFE  430042    682849209.0
           430043    683935437.0
           430044    684472486.0
           430045    685032413.0
           430046    684640908.0
Length: 430047, dtype: float64

In [23]:
stock_data["stock_ret_1d"] = stock_data.groupby('Symbol')['Close'].transform(lambda x: x.pct_change(1))
stock_data["vol_norm"] = stock_data.groupby('Symbol')["Volume"].transform(lambda x: x / x.rolling(window).mean())
stock_data["obv"] = stock_data.groupby('Symbol').apply(lambda g: ta.OBV(g["Close"], g["Volume"]), include_groups=False).reset_index(level=0, drop=True)

/var/folders/jf/1r7jb1_s6ys1p0n0n56s2qsh0000gn/T/ipykernel_5651/2477597040.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  stock_data["stock_ret_1d"] = stock_data.groupby('Symbol')['Close'].transform(lambda x: x.pct_change(1))

In [24]:
stock_data

,Date,Open,High,Low,Close,Volume,Symbol,stock_ret_1d,vol_norm,obv
0,2019-09-19,248.479767,260.903748,248.479767,260.903748,7109860.0,360ONE,NaN,NaN,7109860.0
1,2019-09-20,272.917023,273.943787,272.917023,273.943787,2760648.0,360ONE,0.049980,NaN,9870508.0
2,2019-09-23,287.641022,287.641022,287.641022,287.641022,34096.0,360ONE,0.050000,NaN,9904604.0
3,2019-09-24,302.015839,302.015839,302.015839,302.015839,2496652.0,360ONE,0.049975,NaN,12401256.0
4,2019-09-25,317.109436,317.109436,286.922241,288.513733,530580.0,360ONE,-0.044707,NaN,11870676.0
...,...,...,...,...,...,...,...,...,...,...
976725,2025-09-09,1010.000000,1038.699951,1009.200012,1035.599976,1228793.0,ZYDUSLIFE,0.025702,0.974756,682849209.0
976726,2025-09-10,1040.550049,1049.849976,1033.000000,1039.599976,1086228.0,ZYDUSLIFE,0.003863,0.855775,683935437.0
976727,2025-09-11,1039.599976,1048.000000,1030.300049,1043.599976,537049.0,ZYDUSLIFE,0.003848,0.447328,684472486.0
976728,2025-09-12,1048.300049,1054.599976,1042.000000,1044.750000,559927.0,ZYDUSLIFE,0.001102,0.469458,685032413.0
976729,2025-09-15,1047.000000,1047.000000,1033.050049,1036.900024,391505.0,ZYDUSLIFE,-0.007514,0.332238,684640908.0

In [25]:
merged = pd.merge(stock_data, index_data, on='Date', how='left')

In [26]:
merged

,Date,Open,High,Low,Close,Volume,Symbol,stock_ret_1d,vol_norm,obv,Index_Close,index_ret_1d,index_ret_5d,index_ret_20d,index_vol,index_vol_5d,index_vol_20d
0,2019-09-19,248.479767,260.903748,248.479767,260.903748,7109860.0,360ONE,NaN,NaN,7109860.0,10704.799805,-0.012532,-0.025312,-0.028338,0.010585,0.010405,0.010585
1,2019-09-20,272.917023,273.943787,272.917023,273.943787,2760648.0,360ONE,0.049980,NaN,9870508.0,11274.200195,0.053191,0.017904,0.032559,0.015989,0.028478,0.015989
2,2019-09-23,287.641022,287.641022,287.641022,287.641022,34096.0,360ONE,0.050000,NaN,9904604.0,11600.200195,0.028916,0.054228,0.079957,0.016499,0.029629,0.016499
3,2019-09-24,302.015839,302.015839,302.015839,302.015839,2496652.0,360ONE,0.049975,NaN,12401256.0,11588.200195,-0.001034,0.071236,0.070074,0.016504,0.026595,0.016504
4,2019-09-25,317.109436,317.109436,286.922241,288.513733,530580.0,360ONE,-0.044707,NaN,11870676.0,11440.200195,-0.012772,0.055306,0.034577,0.016342,0.029003,0.016342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976725,2025-09-09,1010.000000,1038.699951,1009.200012,1035.599976,1228793.0,ZYDUSLIFE,0.025702,0.974756,682849209.0,24868.599609,0.003853,0.011758,0.020740,0.005733,0.002244,0.005733
976726,2025-09-10,1040.550049,1049.849976,1033.000000,1039.599976,1086228.0,ZYDUSLIFE,0.003863,0.855775,683935437.0,24973.099609,0.004202,0.010441,0.015784,0.005469,0.001818,0.005469
976727,2025-09-11,1039.599976,1048.000000,1030.300049,1043.599976,537049.0,ZYDUSLIFE,0.003848,0.447328,684472486.0,25005.500000,0.001297,0.010964,0.021158,0.005352,0.001738,0.005352
976728,2025-09-12,1048.300049,1054.599976,1042.000000,1044.750000,559927.0,ZYDUSLIFE,0.001102,0.469458,685032413.0,25114.000000,0.004339,0.015076,0.020092,0.005313,0.001562,0.005313
976729,2025-09-15,1047.000000,1047.000000,1033.050049,1036.900024,391505.0,ZYDUSLIFE,-0.007514,0.332238,684640908.0,25069.199219,-0.001784,0.011950,0.017778,0.005349,0.002638,0.005349

In [27]:
with open("../../data/index_stocked_merged.pkl", 'wb') as f:
    pickle.dump(merged, f)

# with open("../../data/index_stocked_merged.pkl", 'rb') as f:
#     merged = pickle.load(f)

In [28]:
regime=regime.reset_index().rename(columns={"index": "Date"})

In [29]:
merged.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Symbol',
       'stock_ret_1d', 'vol_norm', 'obv', 'Index_Close', 'index_ret_1d',
       'index_ret_5d', 'index_ret_20d', 'index_vol', 'index_vol_5d',
       'index_vol_20d'],
      dtype='object')

In [30]:
merged

,Date,Open,High,Low,Close,Volume,Symbol,stock_ret_1d,vol_norm,obv,Index_Close,index_ret_1d,index_ret_5d,index_ret_20d,index_vol,index_vol_5d,index_vol_20d
0,2019-09-19,248.479767,260.903748,248.479767,260.903748,7109860.0,360ONE,NaN,NaN,7109860.0,10704.799805,-0.012532,-0.025312,-0.028338,0.010585,0.010405,0.010585
1,2019-09-20,272.917023,273.943787,272.917023,273.943787,2760648.0,360ONE,0.049980,NaN,9870508.0,11274.200195,0.053191,0.017904,0.032559,0.015989,0.028478,0.015989
2,2019-09-23,287.641022,287.641022,287.641022,287.641022,34096.0,360ONE,0.050000,NaN,9904604.0,11600.200195,0.028916,0.054228,0.079957,0.016499,0.029629,0.016499
3,2019-09-24,302.015839,302.015839,302.015839,302.015839,2496652.0,360ONE,0.049975,NaN,12401256.0,11588.200195,-0.001034,0.071236,0.070074,0.016504,0.026595,0.016504
4,2019-09-25,317.109436,317.109436,286.922241,288.513733,530580.0,360ONE,-0.044707,NaN,11870676.0,11440.200195,-0.012772,0.055306,0.034577,0.016342,0.029003,0.016342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976725,2025-09-09,1010.000000,1038.699951,1009.200012,1035.599976,1228793.0,ZYDUSLIFE,0.025702,0.974756,682849209.0,24868.599609,0.003853,0.011758,0.020740,0.005733,0.002244,0.005733
976726,2025-09-10,1040.550049,1049.849976,1033.000000,1039.599976,1086228.0,ZYDUSLIFE,0.003863,0.855775,683935437.0,24973.099609,0.004202,0.010441,0.015784,0.005469,0.001818,0.005469
976727,2025-09-11,1039.599976,1048.000000,1030.300049,1043.599976,537049.0,ZYDUSLIFE,0.003848,0.447328,684472486.0,25005.500000,0.001297,0.010964,0.021158,0.005352,0.001738,0.005352
976728,2025-09-12,1048.300049,1054.599976,1042.000000,1044.750000,559927.0,ZYDUSLIFE,0.001102,0.469458,685032413.0,25114.000000,0.004339,0.015076,0.020092,0.005313,0.001562,0.005313
976729,2025-09-15,1047.000000,1047.000000,1033.050049,1036.900024,391505.0,ZYDUSLIFE,-0.007514,0.332238,684640908.0,25069.199219,-0.001784,0.011950,0.017778,0.005349,0.002638,0.005349

In [ ]:
def add_indicators(df: pd.DataFrame, window:int=20) -> pd.DataFrame:
    """
    Add stock-only indicators + stock-index relationship features
    for a stacked dataframe of multiple stocks.
    
    Required columns:
    ['Symbol','Date','Open','High','Low','Close','Volume','Index_Close']
    """

    df = df.copy()

    grouped = df.groupby("Symbol", group_keys=False)

    # ------------------------------
    # 1. Trend / Moving Averages
    # ------------------------------
    df["EMA_9"]   = grouped["Close"].transform(lambda x: ta.EMA(x, 9))
    df["EMA_30"]  = grouped["Close"].transform(lambda x: ta.EMA(x, 30))
    df["EMA_100"] = grouped["Close"].transform(lambda x: ta.EMA(x, 100))

    # Price ratios
    # df["ema_9_ratio"]   = df["Close"] / df["EMA_9"]
    # df["ema_30_ratio"]  = df["Close"] / df["EMA_30"]
    # df["ema_100_ratio"] = df["Close"] / df["EMA_100"]

    # ------------------------------
    # 2. Directional Indicators
    # ------------------------------
    df["plus_di"]  = grouped.apply(lambda g: ta.PLUS_DI(g["High"], g["Low"], g["Close"], timeperiod=14), include_groups=False)
    df["minus_di"] = grouped.apply(lambda g: ta.MINUS_DI(g["High"], g["Low"], g["Close"], timeperiod=14), include_groups=False)
    df["adx"]      = grouped.apply(lambda g: ta.ADX(g["High"], g["Low"], g["Close"], timeperiod=14), include_groups=False)


    # ------------------------------
    # 3. Oscillators / Momentum
    # ------------------------------
    df["rsi"] = grouped["Close"].transform(lambda x: ta.RSI(x, 14))

    

    for n in [5, 14, 30]:
        df[f"roc_{n}"] = grouped["Close"].transform(lambda x: ta.ROC(x, n))


    # ------------------------------
    # 4. ATR-based Volatility
    # ------------------------------
    for n in [5, 14, 30]:
        df[f"atr_{n}"] = grouped.apply(lambda g: ta.ATR(g["High"], g["Low"], g["Close"], timeperiod=n), include_groups=False)
        df[f"atr_{n}"] = df[f"atr_{n}"] / df["Close"]

    # ------------------------------
    # 5. Returns & Rolling Volatility
    # ------------------------------
    # df["stock_ret_1d"]  = grouped["Close"].transform(lambda x: x.pct_change(1))

    # for n in [5, 14, 30]:
    #     df[f"stock_ret_{n}d"] = grouped["Close"].transform(lambda x: x.pct_change(n))

    for n in [5, 14, 30]:
        df[f"vol_{n}d"] = grouped["stock_ret_1d"].transform(lambda x: x.rolling(n).std())

    # ------------------------------
    # 6. Rolling Highs normalized
    # ------------------------------
    for n in [5, 14, 30]:
        df[f"{n}_days_high"] = grouped["High"].transform(lambda x: x.rolling(n).max()) / df["Close"]

    # ------------------------------
    # 7. MACD (normalized by Close)
    # ------------------------------
    def macd_apply(x):
        macd, macd_signal, macd_hist = ta.MACD(x, fastperiod=12, slowperiod=26, signalperiod=9)
        return pd.DataFrame({"macd": macd, "macd_signal": macd_signal, "macd_hist": macd_hist}, index=x.index)

    macd_df = grouped["Close"].apply(macd_apply)
    macd_df["macd"]        = macd_df["macd"] / df["Close"]
    macd_df["macd_signal"] = macd_df["macd_signal"] / df["Close"]
    macd_df["macd_hist"]   = macd_df["macd_hist"] / df["Close"]
    df = df.join(macd_df)


    # ------------------------------
    # 8. Stock vs Index Features
    # ------------------------------

    # relative return
    df["rel_ret"] = df["stock_ret_1d"] - df["index_ret_1d"]

    # rolling beta
    def rolling_beta(stock_ret, index_ret, win=20):
        cov = stock_ret.rolling(win).cov(index_ret)
        var = index_ret.rolling(win).var()
        return cov / var
    

    df["beta"] = grouped.apply(lambda g: rolling_beta(g["stock_ret_1d"], g["index_ret_1d"], window), include_groups=False)

    # rolling correlation
    df["corr"] = grouped.apply(lambda g: g["stock_ret_1d"].rolling(window).corr(g["index_ret_1d"]), include_groups=False)

    # excess volatility
    df["stock_vol"] = grouped["stock_ret_1d"].transform(lambda x: x.rolling(window).std())
    df["excess_vol"] = df["stock_vol"] - df["index_vol"]

    # ------------------------------
    # 9. Range-Based Volatility
    # ------------------------------
    df["parkinson_vol"] = grouped.apply(lambda g: np.sqrt(1/(4*np.log(2)) * (np.log(g["High"]/g["Low"]))**2), include_groups=False)

    df["gk_vol"] = grouped.apply(
        lambda g: np.sqrt(
            0.5*(np.log(g["High"]/g["Low"]))**2 -
            (2*np.log(2)-1)*(np.log(g["Close"]/g["Open"]))**2
        ),
        include_groups=False
    )
    df["vol_of_vol"] = grouped["stock_ret_1d"].transform(lambda x: x.rolling(window).std().rolling(window).std())

    # ------------------------------
    # 10. Distribution Shape
    # ------------------------------
    df["skew"] = grouped["stock_ret_1d"].transform(lambda x: x.rolling(window).skew())
    df["kurt"] = grouped["stock_ret_1d"].transform(lambda x: x.rolling(window).kurt())

    def downside_semivariance(x):
        neg = x[x < 0]
        return (neg**2).mean()

    df["dsv"] = grouped["stock_ret_1d"].transform(lambda x: x.rolling(window).apply(downside_semivariance, raw=False))

    # ------------------------------
    # 11. Volume Features
    # ------------------------------
    # df["vol_norm"] = grouped["Volume"].transform(lambda x: x / x.rolling(window).mean()) # drop it later
    df["vol_z"] = grouped["vol_norm"].transform(lambda x: (x - x.rolling(window).mean()) / x.rolling(window).std())

    df["vol_vol_ratio"] = grouped.apply(
        lambda g: (g["Volume"] / g["Volume"].rolling(window).mean()) / g["stock_ret_1d"].rolling(window).std(),
        include_groups=False
    )

    # df["obv"] = grouped.apply(lambda g: ta.OBV(g["Close"], g["Volume"]), include_groups=False) # drop it later
    df["obv_z"] = grouped["obv"].transform(lambda x: (x - x.rolling(window).mean()) / x.rolling(window).std())


    df["vwap_dev"] = grouped.apply(
        lambda g: (g["Close"] - (g["High"]+g["Low"]+g["Close"])/3) / ta.ATR(g["High"], g["Low"], g["Close"], timeperiod=14),
        include_groups=False
    )

    return df

In [32]:
modified = add_indicators(merged, window=window)

/opt/miniconda3/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [34]:
modified.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Symbol',
       'stock_ret_1d', 'vol_norm', 'obv', 'Index_Close', 'index_ret_1d',
       'index_ret_5d', 'index_ret_20d', 'index_vol', 'index_vol_5d',
       'index_vol_20d', 'EMA_9', 'EMA_30', 'EMA_100', 'plus_di', 'minus_di',
       'adx', 'rsi', 'roc_5', 'roc_14', 'roc_30', 'atr_5', 'atr_14', 'atr_30',
       'vol_5d', 'vol_14d', 'vol_30d', '5_days_high', '14_days_high',
       '30_days_high', 'macd', 'macd_signal', 'macd_hist', 'rel_ret', 'beta',
       'corr', 'stock_vol', 'excess_vol', 'parkinson_vol', 'gk_vol',
       'vol_of_vol', 'skew', 'kurt', 'dsv', 'vol_z', 'vol_vol_ratio', 'obv_z',
       'vwap_dev'],
      dtype='object')

In [35]:
modified.iloc[388190:388200]

,Date,Open,High,Low,Close,Volume,Symbol,stock_ret_1d,vol_norm,obv,...,parkinson_vol,gk_vol,vol_of_vol,skew,kurt,dsv,vol_z,vol_vol_ratio,obv_z,vwap_dev
388190,2017-05-05,330.401123,334.848328,327.724762,333.882416,1856816.0,HCLTECH,0.014181,0.862864,46720020.0,...,0.012914,0.013739,0.000528,-0.842437,-0.119854,0.000268,0.028652,68.824531,1.739458,0.234427
388191,2017-05-08,333.983063,340.080383,332.312866,338.148560,1581634.0,HCLTECH,0.012777,0.743769,48301654.0,...,0.013876,0.014407,0.000561,-0.824382,-0.241230,0.000268,-0.269980,57.722395,1.764813,0.175623
388192,2017-05-09,340.080353,344.044586,338.047913,341.992035,1814522.0,HCLTECH,0.011366,0.858234,50116176.0,...,0.010560,0.011935,0.000593,-0.941084,-0.160600,0.000303,-0.009504,65.427050,1.789887,0.086266
388193,2017-05-10,341.589478,342.454773,337.303253,339.516785,1515412.0,HCLTECH,-0.007238,0.716247,48600764.0,...,0.009103,0.010028,0.000598,-1.055764,0.449007,0.000258,-0.396122,57.521531,1.375624,-0.033752
388194,2017-05-11,345.231842,345.634308,336.297180,337.544830,7029834.0,HCLTECH,-0.005808,3.009049,41570930.0,...,0.016447,0.013384,0.000605,-0.953551,0.215875,0.000230,3.269107,240.026863,0.222044,-0.311964
388195,2017-05-12,338.068024,341.368225,337.685699,341.146881,3295402.0,HCLTECH,0.010671,1.353122,44866332.0,...,0.006514,0.005203,0.000618,-1.054548,0.282244,0.000262,0.533493,106.368068,0.673180,0.152938
388196,2017-05-15,341.488892,342.092590,340.080261,341.509003,1375146.0,HCLTECH,0.001061,0.575496,46241478.0,...,0.003543,0.004172,0.000643,-1.110823,0.962261,0.000184,-0.714073,52.968662,0.809366,0.042041
388197,2017-05-16,342.092560,344.547577,341.307770,341.931580,5948804.0,HCLTECH,0.001237,2.273372,52190282.0,...,0.005674,0.006674,0.000684,-1.096693,0.935420,0.000184,1.756010,209.180803,1.594650,-0.102894
388198,2017-05-17,342.897552,344.225677,338.953430,343.521362,2747118.0,HCLTECH,0.004649,1.035609,54937400.0,...,0.009270,0.010855,0.000734,-1.235014,1.274479,0.000218,-0.129119,95.969289,1.819906,0.202204
388199,2017-05-18,342.434753,351.047424,339.778503,341.448730,7317362.0,HCLTECH,-0.006033,2.534838,47620038.0,...,0.019595,0.023001,0.000762,-1.105713,0.834062,0.000188,1.830540,231.208018,0.586412,-0.393326

In [36]:
modified.query("Symbol=='TATATECH'").head(10)

,Date,Open,High,Low,Close,Volume,Symbol,stock_ret_1d,vol_norm,obv,...,parkinson_vol,gk_vol,vol_of_vol,skew,kurt,dsv,vol_z,vol_vol_ratio,obv_z,vwap_dev
877829,2023-11-30,1170.154053,1365.179688,1170.154053,1280.343506,46579440.0,TATATECH,NaN,NaN,46579440.0,...,0.092577,0.093556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877830,2023-12-01,1305.989502,1314.473022,1181.465576,1190.241699,18681410.0,TATATECH,-0.070373,NaN,27898030.0,...,0.064068,0.048614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877831,2023-12-04,1190.241699,1203.308472,1122.519165,1162.986938,14740750.0,TATATECH,-0.022898,NaN,13157280.0,...,0.041739,0.046987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877832,2023-12-05,1162.986938,1191.558105,1145.775879,1162.206787,4422358.0,TATATECH,-0.000671,NaN,8734922.0,...,0.023530,0.027701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877833,2023-12-06,1172.104248,1177.418701,1151.626587,1158.940063,2735968.0,TATATECH,-0.002811,NaN,5998954.0,...,0.013302,0.014000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877834,2023-12-07,1163.279419,1169.178955,1150.651489,1156.209717,1624651.0,TATATECH,-0.002356,NaN,4374303.0,...,0.009593,0.010641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877835,2023-12-08,1159.427612,1189.364014,1158.696289,1162.889404,2528210.0,TATATECH,0.005777,NaN,6902513.0,...,0.015689,0.018379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877836,2023-12-11,1169.178955,1238.120483,1163.328125,1206.575073,8017469.0,TATATECH,0.037567,NaN,14919982.0,...,0.037421,0.039476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877837,2023-12-12,1222.811035,1231.635986,1199.407959,1202.577148,2426780.0,TATATECH,-0.003313,NaN,12493202.0,...,0.015924,0.015620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877838,2023-12-13,1213.059692,1252.844971,1205.404907,1219.251709,4281933.0,TATATECH,0.013866,NaN,16775135.0,...,0.023183,0.027111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df = modified.dropna().copy()

In [38]:
def check_if_uptrend(row):
    ema_check = 0
    dmi_check = 0
    if row['EMA_9'] > row['EMA_30'] > row['EMA_100']:
        ema_check = 1
    if row['plus_di'] > row['minus_di'] and row['adx'] > 30:
        dmi_check = 1
    if ema_check and dmi_check:
        return 1
    else:
        return -1

In [39]:
df["is_uptrend"] = df.apply(check_if_uptrend, axis=1)
df["signal"] = df["is_uptrend"].where(df["is_uptrend"] != df["is_uptrend"].shift(), 0)

In [40]:
def build_trades_df(df: pd.DataFrame) -> pd.DataFrame:
    # Ensure proper ordering
    df = df.sort_values(["Symbol", "Date"]).reset_index(drop=True)

    # Shift within symbol
    df["prev_signal"] = df.groupby("Symbol")["signal"].shift(fill_value=0)

    # Mark entry/exit rows
    entries = df.loc[(df["signal"] == 1) & (df["prev_signal"] != 1),
                     ["Symbol", "Date", "Close"]].rename(columns={"Date": "entry_date", "Close": "entry_price"})
    exits = df.loc[(df["signal"] == -1) & (df["prev_signal"] != -1),
                   ["Symbol", "Date", "Close"]].rename(columns={"Date": "exit_date", "Close": "exit_price"})

    # 🚨 Remove exits that occur before the first entry per symbol
    first_entries = entries.groupby("Symbol")["entry_date"].min()
    exits = exits.merge(first_entries, on="Symbol", how="left")
    exits = exits[exits["exit_date"] >= exits["entry_date"]].drop(columns=["entry_date"])

    # Assign trade_id per symbol (after cleaning exits)
    entries["trade_id"] = entries.groupby("Symbol").cumcount()
    exits["trade_id"]   = exits.groupby("Symbol").cumcount()

    # Pair entries with exits (only complete trades survive)
    trades = pd.merge(entries, exits, on=["Symbol", "trade_id"], how="inner").drop(columns=["trade_id"])

    return trades



trades_df = build_trades_df(df)

In [41]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Symbol',
       'stock_ret_1d', 'vol_norm', 'obv', 'Index_Close', 'index_ret_1d',
       'index_ret_5d', 'index_ret_20d', 'index_vol', 'index_vol_5d',
       'index_vol_20d', 'EMA_9', 'EMA_30', 'EMA_100', 'plus_di', 'minus_di',
       'adx', 'rsi', 'roc_5', 'roc_14', 'roc_30', 'atr_5', 'atr_14', 'atr_30',
       'vol_5d', 'vol_14d', 'vol_30d', '5_days_high', '14_days_high',
       '30_days_high', 'macd', 'macd_signal', 'macd_hist', 'rel_ret', 'beta',
       'corr', 'stock_vol', 'excess_vol', 'parkinson_vol', 'gk_vol',
       'vol_of_vol', 'skew', 'kurt', 'dsv', 'vol_z', 'vol_vol_ratio', 'obv_z',
       'vwap_dev', 'is_uptrend', 'signal'],
      dtype='object')

In [42]:
to_drop = [ 'Open', 'High', 'Low', 'Volume', 'EMA_9', 'EMA_30', 'EMA_100', 'is_uptrend', 'signal','obv','vol_norm']

In [43]:
trades_df["return"] = (trades_df["exit_price"] - trades_df["entry_price"])*100/trades_df["entry_price"]

In [44]:
enhanced_trades_df = trades_df.merge(df, left_on=["Symbol", "entry_date"], right_on=["Symbol", "Date"], how="left").drop(columns=["Date", *to_drop]).reset_index(drop=True)

In [45]:
enhanced_trades_df["result"] = np.where(enhanced_trades_df["return"] > 0, 1, 0)

In [46]:
enhanced_trades_df=enhanced_trades_df.merge(n200[["Symbol", "Industry"]], on="Symbol")

In [47]:
enhanced_trades_df

,Symbol,entry_date,entry_price,exit_date,exit_price,return,Close,stock_ret_1d,Index_Close,index_ret_1d,...,vol_of_vol,skew,kurt,dsv,vol_z,vol_vol_ratio,obv_z,vwap_dev,result,Industry
0,360ONE,2020-02-13,336.123260,2020-02-27,315.290924,-6.197826,336.123260,0.042021,12174.650391,-0.002176,...,0.001801,1.963497,5.622271,0.000191,0.552537,53.425084,2.459678,0.240420,0,Financial Services
1,360ONE,2020-08-18,238.884537,2020-09-07,213.087692,-10.798877,238.884537,0.072713,11385.349609,0.012292,...,0.006273,0.216305,1.165620,0.000423,1.443897,67.001571,-0.522190,0.251860,0,Financial Services
2,360ONE,2020-12-15,229.534714,2020-12-21,217.399368,-5.286932,229.534714,-0.002395,13567.849609,0.000715,...,0.002589,1.555079,4.206689,0.000177,-0.655181,18.133108,0.547032,-0.150594,0,Financial Services
3,360ONE,2021-02-11,275.173187,2021-04-12,261.191254,-5.081140,275.173187,0.045592,15173.299805,0.004422,...,0.002420,0.853517,-0.050788,0.000182,-0.288820,40.971301,2.197089,-0.186855,0,Financial Services
4,360ONE,2021-07-19,307.192017,2021-10-08,356.906433,16.183498,307.192017,-0.001836,15752.400391,-0.010739,...,0.003247,1.566200,3.121033,0.000122,1.078679,108.399064,1.999066,-0.002907,1,Financial Services
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8456,ZYDUSLIFE,2023-04-18,504.088043,2023-05-02,505.113983,0.203524,504.088043,0.027485,17660.150391,-0.002637,...,0.002692,1.660169,4.146451,0.000011,2.308264,236.073903,1.461623,0.484949,1,Healthcare
8457,ZYDUSLIFE,2023-06-21,547.276001,2023-08-28,625.555908,14.303552,547.276001,0.007284,18856.849609,0.002134,...,0.000798,0.465201,0.199016,0.000092,-0.071581,79.290502,2.074164,0.092758,1,Healthcare
8458,ZYDUSLIFE,2023-08-29,623.238342,2023-08-30,619.441406,-0.609227,623.238342,-0.003705,19342.650391,0.001896,...,0.001165,0.265467,-0.563798,0.000125,-0.708708,67.572598,-0.570426,-0.152031,0,Healthcare
8459,ZYDUSLIFE,2023-11-09,604.007141,2024-04-12,948.886414,57.098541,604.007141,-0.020393,19395.300781,-0.002479,...,0.002258,1.254320,2.950709,0.000140,0.554319,92.705143,2.027133,-0.284898,1,Healthcare
8460,ZYDUSLIFE,2024-05-22,1065.752808,2024-06-03,1018.020020,-4.478786,1065.752808,-0.007075,22597.800781,0.003052,...,0.002494,-0.530381,-0.253783,0.000486,0.574828,67.534850,1.760228,0.138586,0,Healthcare

In [48]:
regime

           Date  kmeans_cluster  hmm_cluster
0    2015-03-17             2.0          1.0
1    2015-03-18             4.0          1.0
2    2015-03-19             4.0          1.0
3    2015-03-20             4.0          1.0
4    2015-03-21             4.0          1.0
...         ...             ...          ...
3835 2025-09-15             0.0          2.0
3836 2025-09-16             0.0          2.0
3837 2025-09-17             0.0          2.0
3838 2025-09-18             0.0          2.0
3839 2025-09-19             0.0          2.0

[3840 rows x 3 columns]

In [49]:
enhanced_trades_df=enhanced_trades_df.merge(regime, left_on=["entry_date"], right_on=["Date"], how="left").drop(columns=["Date"], axis=1)

In [50]:
enhanced_trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8461 entries, 0 to 8460
Data columns (total 53 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          8461 non-null   object
 1   entry_date      8461 non-null   datetime64[ns]
 2   entry_price     8461 non-null   float32
 3   exit_date       8461 non-null   datetime64[ns]
 4   exit_price      8461 non-null   float32
 5   return          8461 non-null   float32
 6   Close           8461 non-null   float32
 7   stock_ret_1d    8461 non-null   float32
 8   Index_Close     8461 non-null   float64
 9   index_ret_1d    8461 non-null   float64
 10  index_ret_5d    8461 non-null   float64
 11  index_ret_20d   8461 non-null   float64
 12  index_vol       8461 non-null   float64
 13  index_vol_5d    8461 non-null   float64
 14  index_vol_20d   8461 non-null   float64
 15  plus_di         8461 non-null   float64
 16  minus_di        8461 non-null   float64
 17  adx             8461 non-null   float64
 18  rsi             8461 non-null   float64
 19  roc_5           8461 non-null   float64
 20  roc_14          8461 non-null   float64
 21  roc_30          8461 non-null   float64
 22  atr_5           8461 non-null   float64
 23  atr_14          8461 non-null   float64
 24  atr_30          8461 non-null   float64
 25  vol_5d          8461 non-null   float64
 26  vol_14d         8461 non-null   float64
 27  vol_30d         8461 non-null   float64
 28  5_days_high     8461 non-null   float64
 29  14_days_high    8461 non-null   float64
 30  30_days_high    8461 non-null   float64
 31  macd            8461 non-null   float64
 32  macd_signal     8461 non-null   float64
 33  macd_hist       8461 non-null   float64
 34  rel_ret         8461 non-null   float64
 35  beta            8461 non-null   float64
 36  corr            8461 non-null   float64
 37  stock_vol       8461 non-null   float64
 38  excess_vol      8461 non-null   float64
 39  parkinson_vol   8461 non-null   float32
 40  gk_vol          8461 non-null   float32
 41  vol_of_vol      8461 non-null   float64
 42  skew            8461 non-null   float64
 43  kurt            8461 non-null   float64
 44  dsv             8461 non-null   float64
 45  vol_z           8461 non-null   float64
 46  vol_vol_ratio   8461 non-null   float64
 47  obv_z           8461 non-null   float64
 48  vwap_dev        8461 non-null   float64
 49  result          8461 non-null   int64
 50  Industry        8461 non-null   object
 51  kmeans_cluster  8461 non-null   float64
 52  hmm_cluster     8461 non-null   float64
dtypes: datetime64[ns](2), float32(7), float64(41), int64(1), object(2)
memory usage: 3.2+ MB

In [51]:
grouped = enhanced_trades_df.groupby("Industry")["result"].agg(["sum", "count"])
grouped.rename(columns={"sum": "success_count", "count": "total"}, inplace=True)
grouped["fail_count"] = grouped["total"] - grouped["success_count"]

# Step 2: Proportions
total_success = grouped["success_count"].sum()
total_fail = grouped["fail_count"].sum()

grouped["dist_success"] = grouped["success_count"] / total_success
grouped["dist_fail"] = grouped["fail_count"] / total_fail

# Step 3: WoE = log(success_dist / fail_dist)
# add smoothing to avoid divide-by-zero
eps = 1e-6
grouped["WoE"] = np.log((grouped["dist_success"] + eps) / (grouped["dist_fail"] + eps))

# Step 4: Map back to dataframe
enhanced_trades_df["Industry_woe"] = enhanced_trades_df["Industry"].map(grouped["WoE"])

In [52]:
with open('../../data/enhanced_trades_df_v2.pkl', 'wb') as f:
    pickle.dump(enhanced_trades_df, f)

# with open('../../data/enhanced_trades_df_v2.pkl', 'rb') as f:
#     enhanced_trades_df = pickle.load(f)

In [53]:
enhanced_trades_df

,Symbol,entry_date,entry_price,exit_date,exit_price,return,Close,stock_ret_1d,Index_Close,index_ret_1d,...,dsv,vol_z,vol_vol_ratio,obv_z,vwap_dev,result,Industry,kmeans_cluster,hmm_cluster,Industry_woe
0,360ONE,2020-02-13,336.123260,2020-02-27,315.290924,-6.197826,336.123260,0.042021,12174.650391,-0.002176,...,0.000191,0.552537,53.425084,2.459678,0.240420,0,Financial Services,2.0,1.0,-0.045808
1,360ONE,2020-08-18,238.884537,2020-09-07,213.087692,-10.798877,238.884537,0.072713,11385.349609,0.012292,...,0.000423,1.443897,67.001571,-0.522190,0.251860,0,Financial Services,2.0,1.0,-0.045808
2,360ONE,2020-12-15,229.534714,2020-12-21,217.399368,-5.286932,229.534714,-0.002395,13567.849609,0.000715,...,0.000177,-0.655181,18.133108,0.547032,-0.150594,0,Financial Services,0.0,2.0,-0.045808
3,360ONE,2021-02-11,275.173187,2021-04-12,261.191254,-5.081140,275.173187,0.045592,15173.299805,0.004422,...,0.000182,-0.288820,40.971301,2.197089,-0.186855,0,Financial Services,0.0,3.0,-0.045808
4,360ONE,2021-07-19,307.192017,2021-10-08,356.906433,16.183498,307.192017,-0.001836,15752.400391,-0.010739,...,0.000122,1.078679,108.399064,1.999066,-0.002907,1,Financial Services,0.0,2.0,-0.045808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8456,ZYDUSLIFE,2023-04-18,504.088043,2023-05-02,505.113983,0.203524,504.088043,0.027485,17660.150391,-0.002637,...,0.000011,2.308264,236.073903,1.461623,0.484949,1,Healthcare,0.0,2.0,-0.104465
8457,ZYDUSLIFE,2023-06-21,547.276001,2023-08-28,625.555908,14.303552,547.276001,0.007284,18856.849609,0.002134,...,0.000092,-0.071581,79.290502,2.074164,0.092758,1,Healthcare,0.0,2.0,-0.104465
8458,ZYDUSLIFE,2023-08-29,623.238342,2023-08-30,619.441406,-0.609227,623.238342,-0.003705,19342.650391,0.001896,...,0.000125,-0.708708,67.572598,-0.570426,-0.152031,0,Healthcare,0.0,2.0,-0.104465
8459,ZYDUSLIFE,2023-11-09,604.007141,2024-04-12,948.886414,57.098541,604.007141,-0.020393,19395.300781,-0.002479,...,0.000140,0.554319,92.705143,2.027133,-0.284898,1,Healthcare,0.0,2.0,-0.104465
8460,ZYDUSLIFE,2024-05-22,1065.752808,2024-06-03,1018.020020,-4.478786,1065.752808,-0.007075,22597.800781,0.003052,...,0.000486,0.574828,67.534850,1.760228,0.138586,0,Healthcare,0.0,2.0,-0.104465