In [26]:
import yfinance as yf
import pandas as pd
import duckdb as db

In [14]:
n200 = pd.read_csv("../../data/ind_nifty200list.csv")

In [17]:
n200["Industry"].value_counts()

Industry
Financial Services                47
Capital Goods                     19
Automobile and Auto Components    17
Healthcare                        14
Information Technology            13
Fast Moving Consumer Goods        12
Power                             11
Oil Gas & Consumable Fuels        11
Consumer Services                 11
Metals & Mining                   10
Consumer Durables                  6
Realty                             6
Construction Materials             5
Telecommunication                  5
Chemicals                          5
Services                           4
Construction                       3
Textiles                           1
Name: count, dtype: int64

In [18]:
n200[n200["Industry"]=="Capital Goods"]

,Company Name,Industry,Symbol,Series,ISIN Code
0,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022
2,APL Apollo Tubes Ltd.,Capital Goods,APLAPOLLO,EQ,INE702C01027
16,Ashok Leyland Ltd.,Capital Goods,ASHOKLEY,EQ,INE208A01029
18,Astral Ltd.,Capital Goods,ASTRAL,EQ,INE006I01046
32,Bharat Dynamics Ltd.,Capital Goods,BDL,EQ,INE171Z01026
33,Bharat Electronics Ltd.,Capital Goods,BEL,EQ,INE263A01024
35,Bharat Heavy Electricals Ltd.,Capital Goods,BHEL,EQ,INE257A01026
42,CG Power and Industrial Solutions Ltd.,Capital Goods,CGPOWER,EQ,INE067A01029
47,Cochin Shipyard Ltd.,Capital Goods,COCHINSHIP,EQ,INE704P01025
51,Cummins India Ltd.,Capital Goods,CUMMINSIND,EQ,INE298A01020
58,Escorts Kubota Ltd.,Capital Goods,ESCORTS,EQ,INE042A01014
76,Hindustan Aeronautics Ltd.,Capital Goods,HAL,EQ,INE066F01020
123,Mazagoan Dock Shipbuilders Ltd.,Capital Goods,MAZDOCK,EQ,INE249Z01020
147,Polycab India Ltd.,Capital Goods,POLYCAB,EQ,INE455K01017
150,Premier Energies Ltd.,Capital Goods,PREMIERENE,EQ,INE0BS701011
163,Siemens Ltd.,Capital Goods,SIEMENS,EQ,INE003A01024
169,Supreme Industries Ltd.,Capital Goods,SUPREMEIND,EQ,INE195A01028
170,Suzlon Energy Ltd.,Capital Goods,SUZLON,EQ,INE040H01021
196,Waaree Energies Ltd.,Capital Goods,WAAREEENER,EQ,INE377N01017

In [21]:
n200[n200["Industry"]=="Construction"]

,Company Name,Industry,Symbol,Series,ISIN Code
86,IRB Infrastructure Developers Ltd.,Construction,IRB,EQ,INE821I01022
111,Larsen & Toubro Ltd.,Construction,LT,EQ,INE018A01030
154,Rail Vikas Nigam Ltd.,Construction,RVNL,EQ,INE415G01027

In [3]:
from curl_cffi import requests
session = requests.Session(impersonate="chrome")

In [ ]:
sector_indices=['^NSEBANK', "^CNXAUTO", "^CNXIT", "^CNXPHARMA", "^CNXENERGY", "^CNXMETAL", "^CNXINFRA", "^CNXREALTY", "^CNXAUTO", "^CNXFMCG", "^CNXPSUBANK", "^CNXMEDIA", "^CNXCOMMODITIES", "^CNX200", "^CNXFIN", "NIFTY_HEALTHCARE.NS", "NIFTY_OIL_AND_GAS.NS", "NIFTY_PVT_BANK.NS", "NIFTY_FIN_SERVICE.NS"]

In [ ]:
industry_ticker_map = {
  'Capital Goods':"",
 'Construction Materials':"",
 'Financial Services':"^NSEBANK",
 'Power':"^CNXENERGY",
 'Metals & Mining':"^CNXMETAL",
 'Services':"",
 'Oil Gas & Consumable Fuels':"NIFTY_OIL_AND_GAS.NS",
 'Consumer Services':"",
 'Healthcare':"",
 'Automobile and Auto Components':"^CNXAUTO",
 'Consumer Durables':"",
 'Telecommunication':"",
 'Fast Moving Consumer Goods':"^CNXFMCG",
 'Information Technology':"^CNXIT",
 'Realty':"^CNXREALTY",
 'Construction':"",
 'Chemicals':"",
 'Textiles':"",
 }

In [10]:
df=yf.Ticker("NIFTY_PVT_BANK.NS", session=session).history(period='1y')
df=df.drop(["Dividends", "Stock Splits"], axis=1)
df["Volume"] = df["Volume"].astype('int32')
df[["Open", "High", "Low", "Close"]] = df[["Open", "High", "Low", "Close"]].astype('float32')
df.reset_index(inplace=True)
df["Date"] = df["Date"].dt.tz_localize(None)
df.set_index("Date", inplace=True)

In [12]:
df.tail()

                    Open          High           Low         Close  Volume
Date
2025-09-23  26906.550781  27098.349609  26835.900391  27057.400391       0
2025-09-24  26967.750000  27023.849609  26789.849609  26824.599609       0
2025-09-25  26786.699219  26902.750000  26743.599609  26787.500000       0
2025-09-26  26685.050781  26742.849609  26458.000000  26488.449219       0
2025-09-29  26528.849609  26563.750000  26316.400391  26411.300781       0

In [ ]:
import os
import glob

path = '/Users/gautamnaik/Developer/gmmm-backtester/nifty'
all_files = glob.glob(os.path.join(path, "*.csv"))

li = []
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    df['Source'] = os.path.basename(filename.replace("ind_nifty", "").replace("_", "").replace("list.csv", ""))
    li.append(df)
frame = pd.concat(li, axis=0, ignore_index=True)

In [23]:
frame

,Company Name,Industry,Symbol,Series,ISIN Code,Source
0,Anant Raj Ltd.,Realty,ANANTRAJ,EQ,INE242C01024,realty
1,Brigade Enterprises Ltd.,Realty,BRIGADE,EQ,INE791I01019,realty
2,DLF Ltd.,Realty,DLF,EQ,INE271C01023,realty
3,Godrej Properties Ltd.,Realty,GODREJPROP,EQ,INE484J01027,realty
4,Lodha Developers Ltd.,Realty,LODHA,EQ,INE670K01029,realty
...,...,...,...,...,...,...
392,Oracle Financial Services Software Ltd.,Information Technology,OFSS,EQ,INE881D01027,it
393,Persistent Systems Ltd.,Information Technology,PERSISTENT,EQ,INE262H01021,it
394,Tata Consultancy Services Ltd.,Information Technology,TCS,EQ,INE467B01029,it
395,Tech Mahindra Ltd.,Information Technology,TECHM,EQ,INE669C01036,it
396,Wipro Ltd.,Information Technology,WIPRO,EQ,INE075A01022,it

In [ ]:
db.sql("""

""")

In [24]:
frame["Source"].value_counts()

Source
500Healthcare               48
midsmallhealthcare          30
midsmallfinancailservice    30
financialservicesexbank     30
healthcare                  20
pharma                      20
midsmallitAndtelecom        20
financialservices25-50      20
Chemicals                   20
finance                     20
auto                        15
metal                       15
consumerdurables            15
oilgas                      15
fmcg                        15
psubank                     12
bank                        12
realty                      10
media                       10
privatebank                 10
it                          10
Name: count, dtype: int64