In [8]:
import pandas as pd
import pickle
import numpy as np
import talib
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
with open('../../data/nifty_data.pkl', 'rb') as file:
    nifty_data = pickle.load(file)

In [4]:
# download data for 
# S&P 500
# USDINR
# Gold
# India VIX
# ^NSEBANK
# ^CNXIT
# ^CNXFMCG

# sp500_data = yf.Ticker('^GSPC').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)
# usdinr_data = yf.Ticker('USDINR=X').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)
# gold_data = yf.Ticker('GC=F').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)  
# vix_data = yf.Ticker('^INDIAVIX').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)
# nse_bank_data = yf.Ticker('^NSEBANK').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)
# cnx_it_data = yf.Ticker('^CNXIT').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)
# cnx_fmcg_data = yf.Ticker('^CNXFMCG').history(start=nifty_data.index[0].strftime('%Y-%m-%d'), end=nifty_data.index[-1].strftime('%Y-%m-%d'), auto_adjust=True)

In [5]:
# with open('../../data/sp500_data.pkl', 'wb') as file:
#     pickle.dump(sp500_data, file)
# with open('../../data/usdinr_data.pkl', 'wb') as file:
#     pickle.dump(usdinr_data, file)
# with open('../../data/gold_data.pkl', 'wb') as file:
#     pickle.dump(gold_data, file)
# with open('../../data/vix_data.pkl', 'wb') as file:
#     pickle.dump(vix_data, file)
# with open('../../data/nse_bank_data.pkl', 'wb') as file:
#     pickle.dump(nse_bank_data, file)
# with open('../../data/cnx_it_data.pkl', 'wb') as file:
#     pickle.dump(cnx_it_data, file)

with open('../../data/sp500_data.pkl', 'rb') as file:
    sp500_data = pickle.load(file)
with open('../../data/usdinr_data.pkl', 'rb') as file:
    usdinr_data = pickle.load(file)
with open('../../data/gold_data.pkl', 'rb') as file:
    gold_data = pickle.load(file)
with open('../../data/vix_data.pkl', 'rb') as file:
    vix_data = pickle.load(file)
with open('../../data/nse_bank_data.pkl', 'rb') as file:
    nse_bank_data = pickle.load(file)
with open('../../data/cnx_it_data.pkl', 'rb') as file:
    cnx_it_data = pickle.load(file)

In [49]:
sp500_data.index = sp500_data.index.tz_localize(None)
usdinr_data.index = usdinr_data.index.tz_localize(None) 
gold_data.index = gold_data.index.tz_localize(None) 
vix_data.index = vix_data.index.tz_localize(None) 
nse_bank_data.index = nse_bank_data.index.tz_localize(None)
nifty_data.index = nifty_data.index.tz_localize(None)
cnx_it_data.index = cnx_it_data.index.tz_localize(None)

In [50]:
for data, name in zip([sp500_data, usdinr_data, gold_data, vix_data, nse_bank_data, cnx_it_data],
                      ['sp500', 'usdinr', 'gold', 'vix', 'nse_bank', 'cnx_it']):
    data = data.reindex(nifty_data.index)
    data.fillna(method='ffill', inplace=True)
    data.fillna(method='bfill', inplace=True)
    # nifty_data[f'{name}_close'] = data['Close']

/var/folders/jf/1r7jb1_s6ys1p0n0n56s2qsh0000gn/T/ipykernel_3608/3237319926.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
/var/folders/jf/1r7jb1_s6ys1p0n0n56s2qsh0000gn/T/ipykernel_3608/3237319926.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)

In [51]:
df = nifty_data.copy()

In [52]:
df.isnull().sum()

Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [ ]:
df["log_return_1"]  = np.log(df["Close"] / df["Close"].shift(1))
df["log_return_20"] = np.log(df["Close"] / df["Close"].shift(20))
df["rolling_sharpe_20"] = (
    df["log_return_1"].rolling(20).mean() /
    df["log_return_1"].rolling(20).std()
)
log_ret = np.log(df["Close"] / df["Close"].shift(1))
# df["realized_vol_5"]  = np.sqrt((log_ret ** 2).rolling(5).sum())
df["realized_vol_20"] = np.sqrt((log_ret ** 2).rolling(20).sum())
df["realized_vol_60"] = np.sqrt((log_ret ** 2).rolling(60).sum())
df["vol_slope_20"] = df["realized_vol_20"].diff()
df["true_range"] = talib.TRANGE(
    df["High"].values,
    df["Low"].values,
    df["Close"].values
)
range_ratio = (df["High"] - df["Low"]) / df["Close"]
df["range_ratio_20"] = range_ratio.rolling(20).mean()

def rolling_max_drawdown(close, window):
    rolling_max = close.rolling(window).max()
    drawdown = close / rolling_max - 1.0
    return drawdown.rolling(window).min()
# df["rolling_max_dd_20"] = rolling_max_drawdown(df["Close"], 20)
df["rolling_max_dd_60"] = rolling_max_drawdown(df["Close"], 60)
def rolling_autocorr(series, window, lag=1):
    return series.rolling(window).apply(
        lambda x: x.autocorr(lag=lag),
        raw=False
    )

# df["autocorr_5"]  = rolling_autocorr(log_ret, 5)
df["autocorr_20"] = rolling_autocorr(log_ret, 20)

df["vix_slope_20"] = vix_data["Close"].diff().rolling(20).mean()

In [54]:
df["rel_spx_20"] = (
    np.log(df["Close"] / df["Close"].shift(20)) -
    np.log(sp500_data["Close"] / sp500_data["Close"].shift(20))
)
# df["rel_usdinr_20"] = (
#     np.log(df["Close"] / df["Close"].shift(20)) -
#     np.log(usdinr_data["Close"] / usdinr_data["Close"].shift(20))
# )

# df["usdinr_return_20"] = np.log(
#     usdinr_data["Close"] / usdinr_data["Close"].shift(20)
# )
df["usdinr_vol_20"] = (
    np.log(usdinr_data["Close"] / usdinr_data["Close"].shift(1))
    .rolling(20).std()
)

df["rel_gold_20"] = (
    np.log(df["Close"] / df["Close"].shift(20)) -
    np.log(gold_data["Close"] / gold_data["Close"].shift(20))
)
df["vix_level_20"] = vix_data["Close"].rolling(20).mean()
df["vix_slope_20"] = vix_data["Close"].diff().rolling(20).mean()

In [55]:
sector_df = pd.DataFrame({
    "nse_bank": nse_bank_data["Close"],
    "cnx_it": cnx_it_data["Close"]
})

In [56]:
sector_returns = np.log(sector_df / sector_df.shift(1))

In [57]:
daily_dispersion = sector_returns.std(axis=1)
daily_dispersion

Date
2007-09-17         NaN
2007-09-18    0.015977
2007-09-19    0.019617
2007-09-20    0.014390
2007-09-21    0.001249
                ...
2025-09-12    0.000299
2025-09-15    0.005108
2025-09-16    0.002740
2025-09-17    0.000155
2025-09-18    0.002879
Length: 4146, dtype: float64

In [58]:
df["sector_dispersion_20"] = daily_dispersion.rolling(20).mean()

In [59]:
df["trend_strength_200"] = (
    df["Close"] - df["Close"].rolling(200).mean()
) / df["Close"].rolling(200).std()

In [60]:
market_vol = np.log(df["Close"] / df["Close"].shift(1)).rolling(20).std()

df["sector_dispersion_ratio_20"] = (
    daily_dispersion.rolling(20).mean() / market_vol
)

In [61]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'log_return_1', 'log_return_20', 'rolling_sharpe_20', 'realized_vol_20',
       'realized_vol_60', 'vol_slope_20', 'true_range', 'range_ratio_20',
       'rolling_max_dd_60', 'autocorr_20', 'vix_slope_20', 'rel_spx_20',
       'usdinr_vol_20', 'rel_gold_20', 'vix_level_20', 'sector_dispersion_20',
       'trend_strength_200', 'sector_dispersion_ratio_20'],
      dtype='object')

In [ ]:
NEW_FEATURES = [
    'rolling_sharpe_20', 
    'rolling_max_dd_60',

    'realized_vol_20',
    'vol_slope_20', 

    'autocorr_20',

    'rel_spx_20',
    'usdinr_vol_20', 
    'rel_gold_20', 
    'vix_level_20',

    'vix_slope_20', 
    'trend_strength_200',

    'sector_dispersion_ratio_20', 
]
df_feat = df[NEW_FEATURES].dropna()

In [67]:
temp_copy = df_feat.copy()
df_feat = df_feat.drop("Close", axis=1)

In [68]:
df_feat

,log_return_20,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,realized_vol_60,vol_slope_20,range_ratio_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20,sector_dispersion_20
Date,,,,,,,,,,,,,,,,
2008-07-07,-0.110522,-0.224338,-0.254667,0.110180,0.141355,-0.003398,0.033724,-0.219374,-0.027527,0.002786,-0.145529,32.1885,0.2430,-2.110362,0.448846,0.011056
2008-07-08,-0.109431,-0.222237,-0.254667,0.110072,0.141512,-0.000108,0.033671,-0.215630,-0.042579,0.002831,-0.139380,32.4790,0.2905,-2.162983,0.498549,0.012274
2008-07-09,-0.084490,-0.160266,-0.254667,0.116441,0.147411,0.006369,0.035011,-0.235864,0.002960,0.003098,-0.150691,32.7105,0.2315,-1.850902,0.452034,0.011915
2008-07-10,-0.086740,-0.164720,-0.254667,0.116395,0.147115,-0.000045,0.034202,-0.194999,-0.023294,0.002778,-0.153996,32.8575,0.1470,-1.824591,0.454354,0.011963
2008-07-11,-0.109400,-0.203813,-0.254667,0.119516,0.148183,0.003121,0.035888,-0.202349,-0.031528,0.003048,-0.208239,32.9730,0.1155,-1.999600,0.500986,0.013446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-12,0.019893,0.187062,-0.049712,0.023600,0.042602,-0.000214,0.006597,0.116938,0.002157,0.002392,-0.070137,11.3530,-0.1010,1.094953,1.386790,0.007374
2025-09-15,0.017622,0.164607,-0.049712,0.023662,0.042633,0.000062,0.006620,0.116114,-0.007711,0.002327,-0.081116,11.2550,-0.0980,1.037760,1.417814,0.007589
2025-09-16,0.014453,0.141348,-0.049712,0.022518,0.041226,-0.001145,0.006659,0.016878,-0.009692,0.002284,-0.087393,11.1515,-0.1035,1.215327,1.422829,0.007274
2025-09-17,0.013898,0.136405,-0.049712,0.022422,0.041002,-0.000096,0.006521,0.038723,-0.015152,0.002300,-0.091529,11.0745,-0.0770,1.302274,1.421272,0.007240
2025-09-18,0.014782,0.144433,-0.049712,0.022549,0.041064,0.000127,0.006439,0.053860,-0.021480,0.002284,-0.071229,10.9795,-0.0950,1.390504,1.239295,0.006342

In [69]:
mean = df_feat.mean()
std = df_feat.std()

df_feat = (df_feat - mean) / (std + 1e-8)

In [70]:
df_feat

,log_return_20,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,realized_vol_60,vol_slope_20,range_ratio_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20,sector_dispersion_20
Date,,,,,,,,,,,,,,,,
2008-07-07,-1.979133,-1.233993,-1.790170,1.966213,1.088903,-0.832409,2.285305,-1.110913,-0.630254,-0.560954,-2.102724,1.329296,0.784362,-2.212219,-1.425551,0.752250
2008-07-08,-1.961051,-1.225482,-1.790170,1.962786,1.092023,-0.026427,2.279140,-1.092259,-0.957006,-0.545195,-2.014768,1.361443,0.934274,-2.254020,-1.277139,1.136946
2008-07-09,-1.547604,-0.974456,-1.790170,2.165194,1.209489,1.560028,2.433614,-1.193078,0.031579,-0.450395,-2.176565,1.387060,0.748067,-2.006110,-1.416032,1.023520
2008-07-10,-1.584896,-0.992495,-1.790170,2.163750,1.203590,-0.011146,2.340387,-0.989460,-0.538346,-0.563817,-2.223838,1.403327,0.481381,-1.985209,-1.409105,1.038556
2008-07-11,-1.960536,-1.150854,-1.790170,2.262930,1.224857,0.764398,2.534711,-1.026087,-0.717093,-0.468354,-2.999728,1.416108,0.381965,-2.124233,-1.269861,1.506830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-12,0.182761,0.432479,0.656711,-0.785516,-0.877555,-0.052374,-0.841782,0.564802,0.014138,-0.700379,-1.024336,-0.976323,-0.301320,0.334005,1.375161,-0.410826
2025-09-15,0.145118,0.341520,0.656711,-0.783531,-0.876945,0.015284,-0.839119,0.560695,-0.200074,-0.723288,-1.181373,-0.987168,-0.291852,0.288573,1.467799,-0.342798
2025-09-16,0.092581,0.247303,0.656711,-0.819908,-0.904957,-0.280392,-0.834702,0.066239,-0.243083,-0.738806,-1.271157,-0.998621,-0.309210,0.429627,1.482773,-0.442287
2025-09-17,0.083382,0.227282,0.656711,-0.822955,-0.909433,-0.023506,-0.850515,0.175086,-0.361602,-0.732901,-1.330322,-1.007142,-0.225574,0.498696,1.478123,-0.452955
2025-09-18,0.098040,0.259800,0.656711,-0.818910,-0.908186,0.031158,-0.860075,0.250507,-0.498974,-0.738461,-1.039956,-1.017654,-0.282383,0.568784,0.934739,-0.736753

In [79]:
mean = df_feat.mean()
std = df_feat.std()

df_feat = (df_feat - mean) / (std + 1e-8)

In [81]:
df_feat["Close"] = temp_copy["Close"]

In [82]:
df_feat.isnull().sum()

rolling_sharpe_20             0
rolling_max_dd_60             0
realized_vol_20               0
vol_slope_20                  0
autocorr_20                   0
rel_spx_20                    0
usdinr_vol_20                 0
rel_gold_20                   0
vix_level_20                  0
vix_slope_20                  0
trend_strength_200            0
sector_dispersion_ratio_20    0
Close                         0
dtype: int64

In [83]:
with open('../../data/nifty_ts2vec.pkl', 'wb') as file:
    pickle.dump(df_feat, file)

In [14]:
from typing import Dict, Iterable, List
from matplotlib.pyplot import close
from pydantic import BaseModel, Field, ConfigDict
from typing_extensions import Literal
import numpy as np
import pandas as pd
import talib
import enum
import yfinance as yf

# create a enum for the stock names
class StockName(enum.Enum):
    NIFTY = "nifty_data"
    SP500 = "sp500_data"
    USDINR = "usdinr_data"
    GOLD = "gold_data"
    VIX = "vix_data"
    NSE_BANK = "nse_bank_data"
    CNX_IT = "cnx_it_data"


stocks = [
    {"name": "nifty_data", "ticker": "^NSEI"},
    {"name": "sp500_data", "ticker": "^GSPC"},
    {"name": "usdinr_data", "ticker": "USDINR=X"},
    {"name": "gold_data", "ticker": "GC=F"},
    {"name": "vix_data", "ticker": "^INDIAVIX"},
    {"name": "nse_bank_data", "ticker": "^NSEBANK"},
    {"name": "cnx_it_data", "ticker": "^CNXIT"},
]

class OHLCVData(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: Literal["nifty_data", "sp500_data", "usdinr_data", "gold_data", "vix_data", "nse_bank_data", "cnx_it_data"]
    data: pd.DataFrame

class DataObject(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    nifty_data: OHLCVData
    sp500_data: OHLCVData
    usdinr_data: OHLCVData
    gold_data: OHLCVData
    vix_data: OHLCVData
    nse_bank_data: OHLCVData
    cnx_it_data: OHLCVData

class YahooFinanceDataLoader:

    def __init__(self, stock: Dict[str, str]):
        self.stock = stock

    def load_data(self, ticker: str, start: str, end: str) -> pd.DataFrame:
        return yf.Ticker(ticker).history(start=start, end=end, auto_adjust=True)
    
    def clean_data(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        df.index = df.index.tz_localize(None)
        df = df[["Close", "Open", "High", "Low", "Volume"]]
        return df
    
    def run(self, start: str, end: str) -> DataObject:
        data_dict = {}
        for key, ticker in self.stock.items():
            raw_data = self.load_data(ticker, start, end)
            cleaned_data = self.clean_data(raw_data)
            data_dict[key] = OHLCVData(name=key, data=cleaned_data)
        return DataObject(**data_dict)
    
FEATURES = [
    'rolling_sharpe_20', 
    'rolling_max_dd_60',

    'realized_vol_20',
    'vol_slope_20', 

    'autocorr_20',

    'rel_spx_20',
    'usdinr_vol_20', 
    'rel_gold_20', 
    'vix_level_20',

    'vix_slope_20', 
    'trend_strength_200',

    'sector_dispersion_ratio_20', 
]

class FeatureEngineer:
    
    def __init__(self, all_data: DataObject):
        self.all_data = all_data
        self.df = self.all_data.nifty_data.data.copy()

    
    def compute_sector_dispersion(self):
        df = self.df
        nse_bank_data = self.all_data.nse_bank_data.data
        cnx_it_data = self.all_data.cnx_it_data.data

        sector_df = pd.DataFrame({
            "nse_bank": nse_bank_data["Close"],
            "cnx_it": cnx_it_data["Close"]
        })
        sector_returns = np.log(sector_df / sector_df.shift(1))
        daily_dispersion = sector_returns.std(axis=1)
        market_vol = np.log(df["Close"] / df["Close"].shift(1)).rolling(20).std()

        df["sector_dispersion_ratio_20"] = (
            daily_dispersion.rolling(20).mean() / market_vol
        )

    def compute_features(self):

        def rolling_max_drawdown(close, window):
            rolling_max = close.rolling(window).max()
            drawdown = close / rolling_max - 1.0
            return drawdown.rolling(window).min()
        
        def rolling_autocorr(series, window, lag=1):
            return series.rolling(window).apply(
                lambda x: x.autocorr(lag=lag),
                raw=False
            )
        
        df = self.df
        sp500_data = self.all_data.sp500_data.data
        usdinr_data = self.all_data.usdinr_data.data
        gold_data = self.all_data.gold_data.data
        vix_data = self.all_data.vix_data.data


        df["log_return_1"]  = np.log(df["Close"] / df["Close"].shift(1))
        log_ret = np.log(df["Close"] / df["Close"].shift(1))
        df["rolling_sharpe_20"] = (
            df["log_return_1"].rolling(20).mean() /
            df["log_return_1"].rolling(20).std()
        )
        df["rolling_max_dd_60"] = rolling_max_drawdown(df["Close"], 60)
        df["realized_vol_20"] = np.sqrt((log_ret ** 2).rolling(20).sum())
        df["vol_slope_20"] = df["realized_vol_20"].diff()
        df["autocorr_20"] = rolling_autocorr(log_ret, 20)

        df["rel_spx_20"] = (
            np.log(df["Close"] / df["Close"].shift(20)) -
            np.log(sp500_data["Close"] / sp500_data["Close"].shift(20))
        )
        df["usdinr_vol_20"] = (
            np.log(usdinr_data["Close"] / usdinr_data["Close"].shift(1))
            .rolling(20).std()
        )
        df["rel_gold_20"] = (
            np.log(df["Close"] / df["Close"].shift(20)) -
            np.log(gold_data["Close"] / gold_data["Close"].shift(20))
        )
        df["vix_level_20"] = vix_data["Close"].rolling(20).mean()
        df["vix_slope_20"] = vix_data["Close"].diff().rolling(20).mean()
        df["trend_strength_200"] = (
            df["Close"] - df["Close"].rolling(200).mean()
        ) / df["Close"].rolling(200).std()

        # df = df[FEATURES + ["Close"]].dropna()
        # self.df = df

    def post_feature_engineering_cleanup(self):
        df = self.df
        df = df[FEATURES + ["Close"]].dropna()
        self.df = df

    def standardize_features(self):
        df = self.df
        mean = df[FEATURES].mean()
        std = df[FEATURES].std()
        df[FEATURES] = (df[FEATURES] - mean) / (std + 1e-8)

    def run(self):
        self.compute_features()
        print("Features computed", self.df.columns)
        self.compute_sector_dispersion()
        print("Sector dispersion computed", self.df.columns)
        self.post_feature_engineering_cleanup()
        print("Post feature engineering cleanup done", self.df.columns)
        self.standardize_features()
        return self.df[FEATURES + ["Close"]].dropna()


# Usage

In [15]:
data_loader = YahooFinanceDataLoader(stock={stock["name"]: stock["ticker"] for stock in stocks})
all_data = data_loader.run(start="2025-01-01", end="2025-12-31")

In [16]:
feature_engineer = FeatureEngineer(all_data)
df_features = feature_engineer.run()

Features computed Index(['Close', 'Open', 'High', 'Low', 'Volume', 'log_return_1',
       'rolling_sharpe_20', 'rolling_max_dd_60', 'realized_vol_20',
       'vol_slope_20', 'autocorr_20', 'rel_spx_20', 'usdinr_vol_20',
       'rel_gold_20', 'vix_level_20', 'vix_slope_20', 'trend_strength_200'],
      dtype='object')
Sector dispersion computed Index(['Close', 'Open', 'High', 'Low', 'Volume', 'log_return_1',
       'rolling_sharpe_20', 'rolling_max_dd_60', 'realized_vol_20',
       'vol_slope_20', 'autocorr_20', 'rel_spx_20', 'usdinr_vol_20',
       'rel_gold_20', 'vix_level_20', 'vix_slope_20', 'trend_strength_200',
       'sector_dispersion_ratio_20'],
      dtype='object')
Post feature engineering cleanup done Index(['rolling_sharpe_20', 'rolling_max_dd_60', 'realized_vol_20',
       'vol_slope_20', 'autocorr_20', 'rel_spx_20', 'usdinr_vol_20',
       'rel_gold_20', 'vix_level_20', 'vix_slope_20', 'trend_strength_200',
       'sector_dispersion_ratio_20', 'Close'],
      dtype='object')

In [17]:
df_features

,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,vol_slope_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20,Close
Date,,,,,,,,,,,,,
2025-10-20,0.189940,-1.067188,1.878769,0.314399,2.428021,0.511097,0.081952,-2.415461,-1.231261,0.866258,1.443930,0.255842,25843.150391
2025-10-21,0.539634,-1.067188,1.542110,-0.396571,2.274223,0.529070,0.007747,-0.680635,-1.172329,0.510309,1.467377,-0.461972,25868.599609
2025-10-23,0.665448,-1.067188,1.528660,0.051926,2.190078,0.230552,-0.459688,-1.108554,-1.084728,0.707450,1.481708,-0.098621,25891.400391
2025-10-24,0.718418,-1.067188,1.437748,-0.055563,1.736774,0.170924,-0.446006,-0.816969,-0.999516,0.691022,0.897686,0.076298,25795.150391
2025-10-27,1.544395,-1.067188,1.428914,0.058332,0.071893,0.349160,-0.430530,0.421267,-0.913508,0.696498,1.652873,0.087790,25966.050781
2025-10-28,2.502070,-1.067188,0.062372,-1.825681,-0.993894,0.843623,-0.038761,0.938509,-0.872096,0.389833,1.395461,0.814908,25936.199219
2025-10-29,2.900579,-1.067188,0.375702,0.505381,-1.421147,1.269564,-0.092986,1.118808,-0.824314,0.433643,1.867015,0.975169,26053.900391
2025-10-30,2.191720,-1.067188,1.064060,1.025786,-1.210163,1.500720,-0.086649,0.718658,-0.744676,0.652689,0.895162,0.227814,25877.849609
2025-10-31,1.230185,-1.067188,0.352395,-0.916946,0.102362,0.641224,0.095578,0.725230,-0.596551,1.123638,0.045556,-0.067077,25722.099609
2025-11-03,1.187795,-1.067188,0.307528,0.008330,0.019735,0.699153,0.136092,1.001347,-0.388697,1.534349,0.174997,0.099652,25763.349609
2025-11-04,0.335375,-1.067188,0.114194,-0.197688,-0.011770,0.417183,0.141332,1.151328,-0.192789,1.452207,-0.706576,-0.334141,25597.650391
2025-11-06,0.048399,-1.067188,0.277828,0.297657,0.441081,0.707767,0.195130,0.682334,-0.004845,1.397445,-1.197879,-0.297311,25509.699219
2025-11-07,0.159051,-0.724129,0.188328,-0.053603,0.808358,-0.601343,0.207809,0.782880,0.174340,1.337208,-1.339566,-0.513627,25492.300781
2025-11-10,0.048837,-0.724129,-0.112645,-0.347052,0.538992,-0.698168,0.187600,0.850048,0.347949,1.298875,-0.993523,-0.166258,25574.349609
2025-11-11,0.079279,-0.724129,-0.027524,0.188708,0.871067,-0.845726,0.176173,1.059284,0.538283,1.413873,-0.465508,-0.171263,25694.949219
2025-11-12,0.578924,-0.724129,0.661169,1.026250,0.971207,-0.228896,0.254845,0.944771,0.625884,0.707450,0.351295,0.052914,25875.800781
2025-11-13,0.802712,-0.724129,0.498577,-0.155029,1.310721,0.439498,-2.161999,1.678721,0.705521,0.652689,0.291437,0.379553,25879.150391
2025-11-14,0.515701,-0.724129,-0.269776,-0.995609,0.672393,0.434454,-2.119190,1.605674,0.817810,0.877211,0.365107,1.092928,25910.050781
2025-11-17,0.242810,-0.724129,-1.814152,-2.072451,0.078505,1.091162,-2.024032,2.358428,0.891076,0.608880,0.789841,1.699656,26013.449219
2025-11-18,-0.340322,-0.724129,-1.955179,-0.125105,-0.643788,1.066122,-2.085317,0.839635,0.928506,0.362453,0.216957,1.174186,25910.050781
2025-11-19,-0.321858,-0.724129,-1.893241,0.156538,-1.194327,0.639570,-2.070357,0.510027,0.977085,0.439119,0.838216,1.987584,26052.650391
2025-11-20,-0.062676,-0.724129,-1.398831,0.756656,-0.696818,1.895505,-2.335769,1.185270,1.043980,0.565070,1.426321,1.826641,26192.150391
2025-11-21,-0.432567,-0.724129,-1.020757,0.595222,-1.150430,1.529732,-2.241749,0.902613,1.195292,1.145543,0.734577,0.911148,26068.150391
2025-11-24,-0.461993,-0.724129,-0.959581,0.155481,-0.206005,1.355549,-0.229748,0.148268,1.326693,1.008638,0.126280,0.909299,25959.500000
2025-11-25,-1.046709,-0.724129,-1.575948,-0.784707,0.175337,0.567648,0.178682,-0.538829,1.356956,0.313167,-0.307677,1.279537,25884.800781
2025-11-26,-0.290917,0.100470,0.882789,3.482439,-0.465968,0.884812,0.178792,-0.272683,1.358548,0.116026,1.156882,0.038494,26205.300781
2025-11-28,-0.125611,0.831684,-0.150234,-0.931493,-0.768572,0.246933,0.094178,-0.412608,1.308377,-0.141353,0.951660,0.369785,26202.949219
2025-12-01,0.214445,0.870726,-0.733228,-0.738397,-0.633101,0.875980,0.074702,-0.521679,1.266965,-0.179686,0.731528,0.824041,26175.750000
2025-12-02,-0.243821,0.870726,-0.275092,0.706319,-0.324175,0.495327,0.160840,-0.293500,1.152287,-0.683492,-0.030420,0.532649,26032.199219
2025-12-03,0.074685,0.870726,-0.916069,-0.818857,-0.570655,0.004463,0.281347,-0.559466,1.037609,-0.683492,-0.319087,0.864422,25986.000000
2025-12-04,0.426147,0.870726,-1.061159,-0.130742,-0.741497,0.385516,0.226835,-0.317816,0.910986,-0.765634,-0.155378,1.357710,26033.750000
2025-12-05,0.797240,0.870726,-0.492115,0.860220,-0.615347,0.062726,0.530853,-0.176241,0.732598,-1.121585,0.501582,0.756462,26186.449219
2025-12-08,-0.016579,0.870726,0.542447,1.506193,-1.495778,-0.283751,0.522951,-0.196226,0.639422,-0.535636,-0.634679,-0.155855,25960.550781
2025-12-09,-0.539350,0.870726,0.537143,0.063231,-1.143958,0.045961,0.550572,0.118136,0.516781,-0.738254,-1.261941,-0.088215,25839.650391
2025-12-10,-1.108886,0.870726,-0.080697,-0.786752,-0.950655,-0.674502,0.515754,-0.087124,0.421216,-0.552064,-1.699906,-0.371275,25758.000000
2025-12-11,-0.806478,0.870726,0.388312,0.721408,-1.203470,-0.486792,0.575501,0.091645,0.281054,-0.858729,-1.070420,-0.629879,25898.550781
2025-12-12,-0.564391,0.870726,0.868283,0.736619,-0.818953,-0.557429,0.808075,0.021608,0.135317,-0.897062,-0.405401,-1.158772,26046.949219
2025-12-15,-0.818961,0.870726,0.635003,-0.253119,-0.661168,-0.734304,0.823537,-0.673166,0.012676,-0.738254,-0.552466,-1.238256,26027.300781
2025-12-16,-0.950730,0.870726,1.024726,0.611387,-0.251403,-1.185059,0.801543,-0.826560,-0.149785,-1.012061,-1.410025,-1.643506,25860.099609
2025-12-17,-1.343116,0.870726,0.606312,-0.510018,-0.616084,-1.366112,0.740515,-1.257066,-0.319412,-1.061347,-1.646628,-2.218391,25818.550781
2025-12-18,-1.671078,0.870726,0.161245,-0.547003,-0.234398,-1.833033,1.379631,-1.247535,-0.512931,-1.225631,-1.692588,-1.728655,25815.550781
2025-12-19,-1.065472,0.870726,0.341187,0.320286,-0.435941,-2.508078,1.452931,-1.240068,-0.840241,-2.145624,-0.968279,-1.907928,25966.400391
2025-12-22,-0.412031,0.870726,1.030438,1.027024,0.007800,-1.758200,0.939570,-1.282545,-1.123751,-1.844436,0.066499,-1.641057,26172.400391
2025-12-23,-0.242182,0.870726,0.905953,-0.102150,0.721354,-1.084388,0.494820,-1.323240,-1.351514,-1.461105,0.089542,-1.513522,26177.150391
2025-12-24,-1.000661,0.870726,-1.540212,-3.323812,0.900263,-1.465259,0.519538,-1.361374,-1.572906,-1.417297,-0.086609,-0.806245,26142.099609
2025-12-26,-1.260517,0.870726,-1.284801,0.425009,0.950613,-1.320924,1.085082,-1.561506,-1.783149,-1.340630,-0.622962,-0.630455,26042.300781
2025-12-29,-1.461373,2.091935,-1.031345,0.422296,1.110520,-1.055496,1.200785,-0.290509,-1.934460,-0.935395,-1.178954,-0.506303,25942.099609
2025-12-30,-1.405512,2.652049,-1.049607,0.045250,1.078168,-1.203533,1.201490,-0.393127,-2.089753,-0.962776,-1.213020,-0.245901,25938.849609